name: Social
description: Bringing those closest to you... closer.
version: 0.1+3

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0
  camera: 0.2.8
  font_awesome_flutter: 8.2.0
  contacts_service: 0.0.9
  firebase_messaging: 2.1.0
  shared_preferences: 0.5.0
  photo_view: ^0.0.10
  simple_permissions: 0.1.9
  path_provider: 0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/social-marketing-2.png
    - images/icon_cliques.png
    - images/icon_events.png
    - images/icon_meetup.png
    - images/icon_profile.png
    - images/12.png
    - images/man.png
    - images/dinner-test.jpg
    - images/concert-test.jpg

  fonts:
    - family: Watermelon
      fonts:
        - asset: assets/fonts/Watermelon.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoMedium.ttf