name: Social
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  font_awesome_flutter: 8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/social-marketing-2.png
    - images/icon_cliques.png
    - images/icon_events.png
    - images/icon_meetup.png
    - images/icon_profile.png

  fonts:
    - family: Watermelon
      fonts:
        - asset: assets/fonts/Watermelon.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoMedium.ttf